### ISSUE TITLE
All google commands don't work, and mal commands don't work when the bot is hosted on Heroku.

### ISSUE THREAD

**Issue by Dwigoric** [appu1232/Discord-Selfbot#100]
Everytime I trigger the command `>g` and `>i`, the console responds:
```
 No LSB modules are available.
 Ignoring exception in command g
   File "/app/.heroku/python/lib/python3.5/site-packages/discord/ext/commands/core.py", line 50, in wrapped
 Traceback (most recent call last):
   File "/app/cogs/google.py", line 24, in parse_google_card
     ret = yield from coro(*args, **kwargs)
     calculator = node.find(".//table/tr/td/span[@class='nobr']/h2[@class='r']")
   File "/app/cogs/google.py", line 160, in g

     card = self.parse_google_card(card_node)
 The above exception was the direct cause of the following exception:
 AttributeError: 'int' object has no attribute 'find'
 Traceback (most recent call last):

     yield from injected(*ctx.args, **ctx.kwargs)
   File "/app/.heroku/python/lib/python3.5/site-packages/discord/ext/commands/bot.py", line 846, in process_commands
   File "/app/.heroku/python/lib/python3.5/site-packages/discord/ext/commands/core.py", line 54, in wrapped
     yield from command.invoke(ctx)
   File "/app/.heroku/python/lib/python3.5/site-packages/discord/ext/commands/core.py", line 374, in invoke
 discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'int' object has no attribute 'find'
     raise CommandInvokeError(e) from e
```

I separated the mal question since I think the mal command has to save the results to storage and return the results or something idk

**Comment by appu1232** [comment]
A few others have reported the issue as well but it seems very inconsistent and I'm not able to pinpoint what's causing it nor am I able to replicate it myself so it's tough for me to fix it. May have to just settle for a workaround which i'll push in the next update.

**Comment by Dwigoric** [comment]
I see, that's nice! Hope the command will be stable as soon as possible. :)

**Comment by Dwigoric** [comment]
I see; that's nice! I hope the command will be stable as soon as possible. :)
