### ISSUE TITLE
Quote command issue

### ISSUE THREAD

**Issue by GhostOfDawn** [appu1232/Discord-Selfbot#130]
2017-07-30T10:23:44.002102+00:00 app[worker.1]: Ignoring exception in command quote
2017-07-30T10:23:44.002409+00:00 app[worker.1]: Traceback (most recent call last):
2017-07-30T10:23:44.002413+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/discord/ext/commands/core.py", line 50, in wrapped
2017-07-30T10:23:44.002413+00:00 app[worker.1]:     ret = yield from coro(*args, **kwargs)
2017-07-30T10:23:44.002414+00:00 app[worker.1]:   File "/app/cogs/misc.py", line 662, in quote
2017-07-30T10:23:44.002415+00:00 app[worker.1]:     length = len(self.bot.all_log[ctx.message.channel.id + ' ' + ctx.message.server.id])
2017-07-30T10:23:44.002417+00:00 app[worker.1]: AttributeError: 'NoneType' object has no attribute 'id'
2017-07-30T10:23:44.002418+00:00 app[worker.1]: 
2017-07-30T10:23:44.002419+00:00 app[worker.1]: The above exception was the direct cause of the following exception:
2017-07-30T10:23:44.002420+00:00 app[worker.1]: 
2017-07-30T10:23:44.002420+00:00 app[worker.1]: Traceback (most recent call last):
2017-07-30T10:23:44.002422+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/discord/ext/commands/bot.py", line 846, in process_commands
2017-07-30T10:23:44.002422+00:00 app[worker.1]:     yield from command.invoke(ctx)
2017-07-30T10:23:44.002423+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/discord/ext/commands/core.py", line 374, in invoke
2017-07-30T10:23:44.002424+00:00 app[worker.1]:     yield from injected(*ctx.args, **ctx.kwargs)
2017-07-30T10:23:44.002425+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/discord/ext/commands/core.py", line 54, in wrapped
2017-07-30T10:23:44.002425+00:00 app[worker.1]:     raise CommandInvokeError(e) from e
2017-07-30T10:23:44.002426+00:00 app[worker.1]: discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'id'

This comes up when I attempt to use the quote command. Help?

**Comment by appu1232** [comment]
Need more context. Where was this executed, what parameters did you give if any, etc. Note: quote does not work in Private Messages.

**Comment by shivaco** [comment]
Did you use `quote` on 1 week old message?

**Comment by Bluscream** [comment]
My best bet is that he's trying it outside of a server
```
2017-07-30T10:23:44.002415+00:00 app[worker.1]: length = len(self.bot.all_log[ctx.message.channel.id + ' ' + ctx.message.server.id])
2017-07-30T10:23:44.002417+00:00 app[worker.1]: AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by GhostOfDawn** [comment]
Ah, didn't know the quote command wouldn't work in PMs.
