### ISSUE TITLE
time and date command raises error

### ISSUE THREAD

**Issue by drakkillen** [appu1232/Discord-Selfbot#149]
when trying to do time or date command i get this error

Traceback (most recent call last):
  File "C:\Users\[name]\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "C:\Users\[name]\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 374, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\[name]\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: KeyError: 'timezone'

**Comment by shivaco** [comment]
Maybe you typed the wrong timezone? Any mistypes?

**Comment by appu1232** [comment]
Hmm, might be a version compatibility problem when updating from a much older version of the bot. I would recommend re-downloading the latest version of the bot and then manually adding in your values from the `optional_config.json` file to the new one. All other settings files can just be transferred over.

**Comment by drakkillen** [comment]
i didnt know i had to set the time zone. thought it used the computer system time and date
thanks for the reply
