### ISSUE TITLE
Can't use bot after latest updates

### ISSUE THREAD

**Issue by phyne** [appu1232/Discord-Selfbot#160]
I've been using the selfbot without issue for awhile now, but with one of the recent updates, it does not work for me anymore. I have tried reinstalled python 3.5.2 to no avail. Here is what it does on startup:

```
Requirements satisfied.
Starting the bot (this may take a minute or two)...
It is not advised to run the bot as Admin.
Continuing logging in...
It is not advised to run the bot as Admin.
Continuing logging in...
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Max\AppData\Local\Programs\Python\Python35\lib\site-packages\di
scord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "appuselfbot.py", line 491, in on_message
    bot.log_conf = load_log_config()
  File "F:\Software (23 GB)\Discord-Selfbot-master\cogs\utils\checks.py", line 4
1, in load_log_config
    with open('settings/log.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'settings/log.json'
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Max\AppData\Local\Programs\Python\Python35\lib\site-packages\di
scord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "appuselfbot.py", line 491, in on_message
    bot.log_conf = load_log_config()
  File "F:\Software (23 GB)\Discord-Selfbot-master\cogs\utils\checks.py", line 4
1, in load_log_config
    with open('settings/log.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'settings/log.json'
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Max\AppData\Local\Programs\Python\Python35\lib\site-packages\di
scord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "appuselfbot.py", line 491, in on_message
    bot.log_conf = load_log_config()
  File "F:\Software (23 GB)\Discord-Selfbot-master\cogs\utils\checks.py", line 4
1, in load_log_config
    with open('settings/log.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'settings/log.json'
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Max\AppData\Local\Programs\Python\Python35\lib\site-packages\di
scord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "appuselfbot.py", line 491, in on_message
    bot.log_conf = load_log_config()
  File "F:\Software (23 GB)\Discord-Selfbot-master\cogs\utils\checks.py", line 4
1, in load_log_config
    with open('settings/log.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'settings/log.json'
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Max\AppData\Local\Programs\Python\Python35\lib\site-packages\di
scord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "appuselfbot.py", line 491, in on_message
    bot.log_conf = load_log_config()
  File "F:\Software (23 GB)\Discord-Selfbot-master\cogs\utils\checks.py", line 4
1, in load_log_config
    with open('settings/log.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'settings/log.json'
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Max\AppData\Local\Programs\Python\Python35\lib\site-packages\di
scord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "appuselfbot.py", line 491, in on_message
    bot.log_conf = load_log_config()
  File "F:\Software (23 GB)\Discord-Selfbot-master\cogs\utils\checks.py", line 4
1, in load_log_config
    with open('settings/log.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'settings/log.json'
Logged in as
Phyne_
User id:redacted
------
Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\Max\AppData\Local\Programs\Python\Python35\lib\site-packages\di
scord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "appuselfbot.py", line 195, in on_ready
    bot.notify = load_notify_config()
  File "F:\Software (23 GB)\Discord-Selfbot-master\cogs\utils\checks.py", line 3
5, in load_notify_config
    with open('settings/notify.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'settings/notify.json'
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Max\AppData\Local\Programs\Python\Python35\lib\site-packages\di
scord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "appuselfbot.py", line 491, in on_message
    bot.log_conf = load_log_config()
  File "F:\Software (23 GB)\Discord-Selfbot-master\cogs\utils\checks.py", line 4
1, in load_log_config
    with open('settings/log.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'settings/log.json'
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Max\AppData\Local\Programs\Python\Python35\lib\site-packages\di
scord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "appuselfbot.py", line 491, in on_message
    bot.log_conf = load_log_config()
  File "F:\Software (23 GB)\Discord-Selfbot-master\cogs\utils\checks.py", line 4
1, in load_log_config
    with open('settings/log.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'settings/log.json'
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Max\AppData\Local\Programs\Python\Python35\lib\site-packages\di
scord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "appuselfbot.py", line 491, in on_message
    bot.log_conf = load_log_config()
  File "F:\Software (23 GB)\Discord-Selfbot-master\cogs\utils\checks.py", line 4
1, in load_log_config
    with open('settings/log.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'settings/log.json'
```
It seems to log in okay, but the bot is unresponsive in discord.

**Comment by LyricLy** [comment]
Delete your `settings` folder if it exists, and rename your `settings2` folder to `settings`.

**Comment by phyne** [comment]
Thanks!
