### ISSUE TITLE
Embedding doesn't work.

### ISSUE THREAD

**Issue by OffTurned** [appu1232/Discord-Selfbot#162]
Hello, I am having issues with the embed command. I get the following error when I try to use it.

Ignoring exception in command embed
Traceback (most recent call last):
  File "C:\Users\offturned\AppData\Roaming\Python\Python35\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\offturned\Documents\Selfbot\cogs\misc.py", line 172, in embed
    em = discord.Embed(timestamp=timestamp, title=title, description=description, color=int(color, 16))
ValueError: invalid literal for int() with base 16: '0xcyan'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\offturned\AppData\Roaming\Python\Python35\site-packages\discord\ext\commands\bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "C:\Users\offturned\AppData\Roaming\Python\Python35\site-packages\discord\ext\commands\core.py", line 374, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\offturned\AppData\Roaming\Python\Python35\site-packages\discord\ext\commands\core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ValueError: invalid literal for int() with base 16: '0xcyan'

**Comment by appu1232** [comment]
You are giving an improper value for the color field. It is expecting a hex value, not an actual color name. If you want cyan, try `#00FFFF`

**Comment by OffTurned** [comment]
I am not putting anything else. I am only doing <embed test

**Comment by OffTurned** [comment]
http://i.imgur.com/frfJacH.gifv

**Comment by appu1232** [comment]
Then that means the default embed color set in `optional_config.json` is incorrect. Do `>embedcolor #00FFFF` and then try embeding.

**Comment by OffTurned** [comment]
Oh yeah, I remember setting is as "cyan". Didn't know it only supported hex codes.
