### ISSUE TITLE
When installing on heroku

### ISSUE THREAD

**Issue by TheRoyalBlock** [appu1232/Discord-Selfbot#168]
I followed the installations precisely
When running locally it works perfectly
When running on heroku after starting, I get this error repeatedly:
```
2017-08-19T00:27:27.144148+00:00 app[worker.1]: Welcome to Appu's Discord Selfbot!
2017-08-19T00:27:27.144161+00:00 app[worker.1]: 
2017-08-19T00:27:27.144162+00:00 app[worker.1]: Go into your Discord window and press Ctrl+Shift+I (Ctrl+Opt+I can also work on macOS)
2017-08-19T00:27:27.144176+00:00 app[worker.1]: Then, go into the Applications tab (you may have to click the arrow at the top right to get there), expand the 'Local Storage' dropdown, select discordapp, and then grab the token value at the bottom. Here's how it looks: https://imgur.com/h3g9uf6
2017-08-19T00:27:27.144204+00:00 app[worker.1]: Paste the contents of that entry below.
2017-08-19T00:27:27.144206+00:00 app[worker.1]: -------------------------------------------------------------
2017-08-19T00:27:27.144417+00:00 app[worker.1]: | Traceback (most recent call last):
2017-08-19T00:27:27.144437+00:00 app[worker.1]:   File "appuselfbot.py", line 113, in <module>
2017-08-19T00:27:27.144696+00:00 app[worker.1]:     with open('settings/config.json', encoding='utf-8', mode="r") as f:
2017-08-19T00:27:27.144718+00:00 app[worker.1]: FileNotFoundError: [Errno 2] No such file or directory: 'settings/config.json'
2017-08-19T00:27:27.144721+00:00 app[worker.1]: 
2017-08-19T00:27:27.144722+00:00 app[worker.1]: During handling of the above exception, another exception occurred:
2017-08-19T00:27:27.144722+00:00 app[worker.1]: 
2017-08-19T00:27:27.144740+00:00 app[worker.1]: Traceback (most recent call last):
2017-08-19T00:27:27.144756+00:00 app[worker.1]:   File "appuselfbot.py", line 116, in <module>
2017-08-19T00:27:27.144956+00:00 app[worker.1]:     wizard()
2017-08-19T00:27:27.144960+00:00 app[worker.1]:   File "appuselfbot.py", line 93, in wizard
2017-08-19T00:27:27.145146+00:00 app[worker.1]:     config["token"] = input("| ").strip().strip('"')
2017-08-19T00:27:27.145167+00:00 app[worker.1]: EOFError: EOF when reading a line
```
Please help!

**Comment by TheRoyalBlock** [comment]
It seems that the gitignore automatically regenerates, and ignores settings.

**Comment by TheRoyalBlock** [comment]
Deleted gitignore and did everything again, it worked well
