### ISSUE TITLE
Token Not Accepted

### ISSUE THREAD

**Issue by Shugabuga** [appu1232/Discord-Selfbot#19]
I set my token in `/settings/config.json` and despite being valid, it isn't being accepted (see log). What could be the cause? I am using a bot user created from the Discord developer dashboard, and ensured the token value was current/correct.

JSON:
```
{
    "token" : "********************.******************-********",
    "cmd_prefix": "/",
    "customcmd_prefix": "$",
    "bot_identifier": ""
}
```

Logs:
```
Warning: this script is still an alpha, expect bugs
Starting auto-update
Fetching origin
From https://github.com/appu1232/Discord-Selfbot
 * branch            master     -> FETCH_HEAD
The bot is up to date.
Checking requirements...
Using global pip3 executable
Starting bot...
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/discord/http.py", line 258, in static_login
    data = yield from self.request(Route('GET', '/users/@me'))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/discord/http.py", line 200, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: UNAUTHORIZED (status code: 401): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "appuselfbot.py", line 541, in <module>
    bot.run(config['token'], bot=False)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/discord/client.py", line 519, in run
    self.loop.run_until_complete(self.start(*args, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/discord/client.py", line 490, in start
    yield from self.login(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/discord/client.py", line 416, in login
    yield from getattr(self, '_login_' + str(n))(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/discord/client.py", line 346, in _login_1
    data = yield from self.http.static_login(token, bot=is_bot)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/discord/http.py", line 262, in static_login
    raise LoginFailure('Improper token has been passed.') from e
discord.errors.LoginFailure: Improper token has been passed.
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x103930550>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x10456fba8>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x104b36f28>
Task was destroyed but it is pending!
task: <Task pending coro=<game_and_avatar() running at appuselfbot.py:438> wait_for=<Future pending cb=[Task._wakeup()]>>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/discord/http.py", line 258, in static_login
    data = yield from self.request(Route('GET', '/users/@me'))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/discord/http.py", line 200, in request
    raise HTTPException(r, data)
```

Any help would be appreciated.

Python version:
```
$ python3 --version
Python 3.5.3
```
 
Running macOS Sierra `10.12.2`..

**Edit: With fresh install and only adding token the same error occurs.**

**Comment by appu1232** [comment]
This is a selfbot. The bot user token from the Discord developer dashboard is incompatible here. Grab the localstoragetoken, not the bot token. The install instructions in the wiki will tell you how to do this.

**Comment by Shugabuga** [comment]
Damn, was hoping I could use this as a non-selfbot too. So I guess just create a new account, get the token, and use that for the bot?

**Comment by appu1232** [comment]
New account? Sure if you want it to run on that account. Otherwise just use your main account.

**Comment by Shugabuga** [comment]
Okay.

**Comment by aphinhat** [comment]
ทำยังไง
