### ISSUE TITLE
Selfdestruct is broken for me

### ISSUE THREAD

**Issue by TeamGameRevolution** [appu1232/Discord-Selfbot#191]
Get the following error:

```Ignoring exception in command selfdestruct
Traceback (most recent call last):
  File "/root/.local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 62, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/root/Discord-Selfbot/cogs/utility.py", line 195, in selfdestruct
    timer = int(amount.strip())
AttributeError: 'NoneType' object has no attribute 'strip'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.local/lib/python3.5/site-packages/discord/ext/commands/bot.py", line 886, in invoke
    yield from ctx.command.invoke(ctx)
  File "/root/.local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 470, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/root/.local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 71, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'strip'```

**Comment by appu1232** [comment]
`sd` requires requires you to specify a number as an argument as well (the number of seconds to wait before self-destructing). Ex: `>sd 5`
