### ISSUE TITLE
Help is creating error.

### ISSUE THREAD

**Issue by JPlater** [appu1232/Discord-Selfbot#226]
So when I do <help "<" is my prefix it comes up with this

Ignoring exception in command help
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Python\Python35\site-packages\discord\ext\commands\core.py", line 62, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\User\Desktop\Discord\Discord Self Bot\Discord-Selfbot-master\cogs\help.py", line 331, in help
    await self.bot.formatter.format_help_for(ctx, self.bot)
  File "C:\Users\User\Desktop\Discord\Discord Self Bot\Discord-Selfbot-master\cogs\help.py", line 281, in format_help_for
    embed = discord.Embed(color=self.color, **emb['embed'])
  File "C:\Users\User\Desktop\Discord\Discord Self Bot\Discord-Selfbot-master\cogs\help.py", line 83, in color
    return self.me.color
AttributeError: 'ClientUser' object has no attribute 'color'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Python\Python35\site-packages\discord\ext\commands\bot.py", line 886, in invoke
    yield from ctx.command.invoke(ctx)
  File "C:\Users\User\AppData\Roaming\Python\Python35\site-packages\discord\ext\commands\core.py", line 489, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\User\AppData\Roaming\Python\Python35\site-packages\discord\ext\commands\core.py", line 71, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'ClientUser' object has no attribute 'color'

Don't know what this means but hopefully you can help :)

**Comment by appu1232** [comment]
Where are you running the help command.

**Comment by JPlater** [comment]
Yes

**Comment by JPlater** [comment]
Is it broken or did it change commands?

**Comment by appu1232** [comment]
I'm asking where you ran it. Server? DM?

**Comment by JPlater** [comment]
DM But Uhhh did you update it recently because I lost all the commands and don't know how to navigate through the new help.

**Comment by JPlater** [comment]
Just figured out why it wasn't working.
