### ISSUE TITLE
Help error in channels

### ISSUE THREAD

**Issue by marcocorriero** [appu1232/Discord-Selfbot#242]
Ignoring exception in command help
Traceback (most recent call last):
  File "C:\Users\marco\AppData\Roaming\Python\Python35\site-packages\discord\ext\commands\core.py", line 62, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\marco\Desktop\Discord-Selfbot-2.0.0\cogs\help.py", line 332, in help
    await self.bot.formatter.format_help_for(ctx, self.bot)
  File "C:\Users\marco\Desktop\Discord-Selfbot-2.0.0\cogs\help.py", line 282, in format_help_for
    embed = discord.Embed(color=self.color, **emb['embed'])
  File "C:\Users\marco\Desktop\Discord-Selfbot-2.0.0\cogs\help.py", line 83, in color
    return self.me.color
AttributeError: 'ClientUser' object has no attribute 'color'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\marco\AppData\Roaming\Python\Python35\site-packages\discord\ext\commands\bot.py", line 886, in invoke
    yield from ctx.command.invoke(ctx)
  File "C:\Users\marco\AppData\Roaming\Python\Python35\site-packages\discord\ext\commands\core.py", line 489, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\marco\AppData\Roaming\Python\Python35\site-packages\discord\ext\commands\core.py", line 71, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'ClientUser' object has no attribute 'color'

**Comment by opabravo** [comment]
It's fixed
