### ISSUE TITLE
core.py error

### ISSUE THREAD

**Issue by hlugt** [appu1232/Discord-Selfbot#272]
I first got error in client.py, but somehow the optional_config.json got erased. 

Now I am left with this one:

Ignoring exception in command quote
Traceback (most recent call last):
  File "/home/..../.local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 62, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/..../Discord-Selfbot/cogs/misc.py", line 670, in quote
    channels = [ctx.channel] + [x for x in ctx.guild.channels if x != ctx.channel and type(x) == discord.channel.TextChannel]
AttributeError: 'NoneType' object has no attribute 'channels'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/..../.local/lib/python3.5/site-packages/discord/ext/commands/bot.py", line 886, in invoke
    yield from ctx.command.invoke(ctx)
  File "/home/..../.local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 489, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/home/..../.local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 71, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'channels'

please advice, maybe also some config which got deleted?

**Comment by chenzw95** [comment]
Please tell us more about what you were doing that led to the error. Also, files don't delete themselves, so it would be good if you can explain the circumstances leading to `optional_config.json` "somehow" getting deleted.

**Comment by hlugt** [comment]
Ok, sorry can not reproduce. Tried same commands and now I get no error. The file was actually not itself deleted: the content was gone. I think it was after the commandline update, it was working before that. I will keep an eye out: I understand this is not very helpfull... Thanks for your time...
