### ISSUE TITLE
TypeError (log)

### ISSUE THREAD

**Issue by shikhir-arora** [appu1232/Discord-Selfbot#277]
I've had this issue for a while, but it hasn't bothered me since it doesn't cause the bot to crash or anything. 

```bash
2|Appu     | Ignoring exception in voice_state_update
2|Appu     | Traceback (most recent call last):
2|Appu     |   File "/home/vlexar/.local/lib/python3.6/site-packages/discord/client.py", line 223, in _run_event
2|Appu     | TypeError: on_voice_state_update() takes 3 positional arguments but 4 were given
2|Appu     | Ignoring exception in voice_state_update
2|Appu     | Traceback (most recent call last):
2|Appu     |   File "/home/vlexar/.local/lib/python3.6/site-packages/discord/client.py", line 223, in _run_event
2|Appu     | TypeError: on_voice_state_update() takes 3 positional arguments but 4 were given
2|Appu     | Ignoring exception in voice_state_update
2|Appu     | Traceback (most recent call last):
2|Appu     |   File "/home/vlexar/.local/lib/python3.6/site-packages/discord/client.py", line 223, in _run_event
2|Appu     | TypeError: on_voice_state_update() takes 3 positional arguments but 4 were given
2|Appu     | Ignoring exception in voice_state_update
2|Appu     | Traceback (most recent call last):
2|Appu     |   File "/home/vlexar/.local/lib/python3.6/site-packages/discord/client.py", line 223, in _run_event
2|Appu     | TypeError: on_voice_state_update() takes 3 positional arguments but 4 were given
2|Appu     | Ignoring exception in voice_state_update
2|Appu     | Traceback (most recent call last):
2|Appu     |   File "/home/vlexar/.local/lib/python3.6/site-packages/discord/client.py", line 223, in _run_event
2|Appu     | TypeError: on_voice_state_update() takes 3 positional arguments but 4 were given
``` 

Which just occurs every few minutes while in VC (from the log here). I'm on the latest version, but yeah, was just curious if that was normal. As noted it doesn't affect anything for the functionality.

**Comment by LyricLy** [comment]
You are using an outdated custom cog, likely `antimove.py`. Delete this file from your `custom_cogs` directory.

**Comment by shikhir-arora** [comment]
Removed it, thanks 👍
