### ISSUE TITLE
Quote command does not work

### ISSUE THREAD

**Issue by TheRoyalBlock** [appu1232/Discord-Selfbot#282]
# Problem
Quote command does not work

# Output in server
An error occurred with the quote command. Check the console for details.

# Output in console
```
Ignoring exception in command quote
Traceback (most recent call last):
  File "C:\Users\---\AppData\Roaming\Python\Python36\site-packages\discord\ext\commands\core.py", line 62, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\---\Desktop\Discord Selfbot\cogs\misc.py", line 729, in quote
    color = int('0x' + color, 16)
ValueError: invalid literal for int() with base 16: '0xrandom'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\---\AppData\Roaming\Python\Python36\site-packages\discord\ext\commands\bot.py", line 886, in invoke
    yield from ctx.command.invoke(ctx)
  File "C:\Users\---\AppData\Roaming\Python\Python36\site-packages\discord\ext\commands\core.py", line 493, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\---\AppData\Roaming\Python\Python36\site-packages\discord\ext\commands\core.py", line 71, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ValueError: invalid literal for int() with base 16: '0xrandom'
```

**Comment by SuperOP535** [comment]
found ya

**Comment by JonnyBoy2000** [comment]
@TheRoyalBlock The reason why that error is being thrown is because my guess is that you used random as a color code in the `quotecolor` command. To fix this issue just clear your setting and retype the command and use an actual color hex code.
