### ISSUE TITLE
>serverinfo command is causing exceptions

### ISSUE THREAD

**Issue by karb0n13** [appu1232/Discord-Selfbot#292]
When attempting to invoke the `>serverinfo` command I am getting:
`An error occurred with the serverinfo command. Check the console for details.`

The console shows:
```
Ignoring exception in command serverinfo
Traceback (most recent call last):
  File "/home/<userfolder>/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 62, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/media/5TB-Storage/karb0n13_bot/cogs/serverinfo.py", line 88, in serverinfo
    url = PythonGists.Gist(description='All Users in: %s' % server.name, content=str(all), name='server.txt')
  File "/home/<userfolder>/.local/lib/python3.6/site-packages/PythonGists/gist.py", line 48, in Gist
    uniqueID=r.json()['url']
KeyError: 'url'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/<userfolder>/.local/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 886, in invoke
    yield from ctx.command.invoke(ctx)
  File "/home/<userfolder>/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 909, in invoke
    yield from super().invoke(ctx)
  File "/home/<userfolder>/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 498, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/home/<userfolder>/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 71, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: KeyError: 'url'
```
has something changed on discord's end?

**Comment by karb0n13** [comment]
was informed via discord:
` it's because creating anonymous gists are now deprecated from GitHub since March 19, 2018 19:00 UTC (11:00 am PST). Read more about it here https://blog.github.com/2018-02-18-deprecation-notice-removing-anonymous-gist-creation/`
so I will be waiting for the next release :)

**Comment by chenzw95** [comment]
Re-opening this issue so that we can track this.
