### ISSUE TITLE
No module named 'pip._vendor.urllib3'

### ISSUE THREAD

**Issue by Chizz3x** [appu1232/Discord-Selfbot#304]
```
Traceback (most recent call last):
File "C:\Users\drebu.UNKNOWN-CH\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 193, in _run_module_as_main       "__main__", mod_spec)
File "C:\Users\drebu.UNKNOWN-CH\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 85, in _run_code            exec(code, run_globals)
File "C:\Users\drebu.UNKNOWN-CH\AppData\Roaming\Python\Python36\site-packages\pip\__main__.py", line 16, in <module>      from pip._internal import main as _main  # noqa                                                                       
File "C:\Users\drebu.UNKNOWN-CH\AppData\Roaming\Python\Python36\site-packages\pip\_internal\__init__.py", line 20, in <module>            from pip._vendor.urllib3.exceptions import DependencyWarning
ModuleNotFoundError: No module named 'pip._vendor.urllib3'
Traceback (most recent call last):
File "C:\Users\drebu.UNKNOWN-CH\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 193, in _run_module_as_main                             "__main__", mod_spec)
File "C:\Users\drebu.UNKNOWN-CH\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 85, in _run_code            exec(code, run_globals)
File "C:\Users\drebu.UNKNOWN-CH\AppData\Roaming\Python\Python36\site-packages\pip\__main__.py", line 16, in <module>      from pip._internal import main as _main  # noqa
File "C:\Users\drebu.UNKNOWN-CH\AppData\Roaming\Python\Python36\site-packages\pip\_internal\__init__.py", line 20, in <module>
from pip._vendor.urllib3.exceptions import DependencyWarning
ModuleNotFoundError: No module named 'pip._vendor.urllib3'
Requirements installation failed. Perhaps some dependency is missing or access was denied? Possible solutions:          
- Run as administrator                                                                                                  
- Google the error                                                                                                      
- Visit the Discord server for help                                                                                     
Press any key to exit.
```

I am getting this error for like 4 days now, tried to google it but found nothing usefull. I see that i am missing some modules, am i right? Btv reinstalling Python didn't help too.

**Comment by Chizz3x** [comment]
The issue got fixed :/
Still now new problems with cog's
Any help?

**Comment by chenzw95** [comment]
We are addressing only issues with code here, and will not be able to assist with configuration issues arising from user error.
