### ISSUE TITLE
I don't understand this. Please help!

### ISSUE THREAD

**Issue by ElijahChase** [appu1232/Discord-Selfbot#314]
Traceback (most recent call last):
  File "appuselfbot.py", line 130, in <module>
    data = load(f)  # checks if the settings file is valid json file
  File "C:\Users\skill\AppData\Local\Programs\Python\Python36-32\lib\json\__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\skill\AppData\Local\Programs\Python\Python36-32\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\skill\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\skill\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 2 column 14 (char 15)

Keeps repeating. I don't get it, I ran run.bat with administrator, and this is happening!

**Comment by LyricLy** [comment]
We are unable to assist users with errors caused by their own behaviour due to our [policy on support](https://github.com/appu1232/Discord-Selfbot/blob/master/issue_template.md).
