### ISSUE TITLE
Issue with the Custom Cogs Command (Not the Custom Cogs themselves)

### ISSUE THREAD

**Issue by JackyXteam** [appu1232/Discord-Selfbot#337]
***Cog list:***
```Python
Traceback (most recent call last):
  File "C:\Users\radwa\AppData\Roaming\Python\Python36\site-packages\discord\ext\commands\core.py", line 60, in wrapped
    ret = await coro(*args, **kwargs)
  File "D:\Windows files\Desktop\All bots\Jacky's Bot\cogs\cog_download.py", line 138, in list
    found_cog = response.json()
  File "C:\Users\radwa\AppData\Roaming\Python\Python36\site-packages\requests\models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\radwa\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\radwa\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\radwa\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\radwa\AppData\Roaming\Python\Python36\site-packages\discord\ext\commands\bot.py", line 876, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\radwa\AppData\Roaming\Python\Python36\site-packages\discord\ext\commands\core.py", line 913, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "C:\Users\radwa\AppData\Roaming\Python\Python36\site-packages\discord\ext\commands\core.py", line 503, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\radwa\AppData\Roaming\Python\Python36\site-packages\discord\ext\commands\core.py", line 69, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

***Cog Update:***
```Python
Traceback (most recent call last):
  File "C:\Users\radwa\AppData\Roaming\Python\Python36\site-packages\discord\ext\commands\core.py", line 60, in wrapped
    ret = await coro(*args, **kwargs)
  File "D:\Windows files\Desktop\All bots\Jacky's Bot\cogs\cog_download.py", line 186, in update
    cog = requests.get("http://appucogs.tk/cogs/{}.json".format(entry)).json()
  File "C:\Users\radwa\AppData\Roaming\Python\Python36\site-packages\requests\models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\radwa\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\radwa\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\radwa\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\radwa\AppData\Roaming\Python\Python36\site-packages\discord\ext\commands\bot.py", line 876, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\radwa\AppData\Roaming\Python\Python36\site-packages\discord\ext\commands\core.py", line 913, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "C:\Users\radwa\AppData\Roaming\Python\Python36\site-packages\discord\ext\commands\core.py", line 503, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\radwa\AppData\Roaming\Python\Python36\site-packages\discord\ext\commands\core.py", line 69, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

***Cog install:***
```Python
Traceback (most recent call last):
  File "C:\Users\radwa\AppData\Roaming\Python\Python36\site-packages\discord\ext\commands\core.py", line 60, in wrapped
    ret = await coro(*args, **kwargs)
  File "D:\Windows files\Desktop\All bots\Jacky's Bot\cogs\cog_download.py", line 59, in install
    cog = response.json()
  File "C:\Users\radwa\AppData\Roaming\Python\Python36\site-packages\requests\models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\radwa\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\radwa\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\radwa\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\radwa\AppData\Roaming\Python\Python36\site-packages\discord\ext\commands\bot.py", line 876, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\radwa\AppData\Roaming\Python\Python36\site-packages\discord\ext\commands\core.py", line 913, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "C:\Users\radwa\AppData\Roaming\Python\Python36\site-packages\discord\ext\commands\core.py", line 503, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\radwa\AppData\Roaming\Python\Python36\site-packages\discord\ext\commands\core.py", line 69, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by LyricLy** [comment]
Domain name expired. Give me a minute.

**Comment by skoof** [comment]
I'm also having this issue

**Comment by LyricLy** [comment]
This should be fixed. Are you all sure your errors are exactly the same?
