### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by CS223** [appu1232/Discord-Selfbot#344]
Hey everytime I start up the bot it gives me this error i'm on a mac version macos high sierra and i don't understand how to fix it so if you guys can help that would mean a lot 
Here is a hastebin so the code looks better https://hastebin.com/anumisamav.sql

Starting bot...
It is not advised to run the bot with root privileges.
Continuing logging in...
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/connector.py", line 822, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 804, in create_connection
    sock, protocol_factory, ssl, server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 830, in _create_connection_transport
    yield from waiter
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/sslproto.py", line 505, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/sslproto.py", line 201, in feed_ssldata
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "appuselfbot.py", line 911, in <module>
    bot.run(token, bot=False)
  File "/Users/CS/Library/Python/3.6/lib/python/site-packages/discord/client.py", line 568, in run
    return task.result()
  File "/Users/CS/Library/Python/3.6/lib/python/site-packages/discord/client.py", line 475, in start
    await self.login(*args, bot=bot)
  File "/Users/CS/Library/Python/3.6/lib/python/site-packages/discord/client.py", line 346, in login
    await self.http.static_login(token, bot=bot)
  File "/Users/CS/Library/Python/3.6/lib/python/site-packages/discord/http.py", line 247, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "/Users/CS/Library/Python/3.6/lib/python/site-packages/discord/http.py", line 154, in request
    async with self._session.request(method, url, **kwargs) as r:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/client.py", line 843, in __aenter__
    self._resp = await self._coro
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/client.py", line 366, in _request
    timeout=timeout
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/connector.py", line 445, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/connector.py", line 757, in _create_connection
    req, traces, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/connector.py", line 879, in _create_direct_connection
    raise last_exc
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/connector.py", line 862, in _create_direct_connection
    req=req, client_error=client_error)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/connector.py", line 827, in _wrap_create_connection
    raise ClientConnectorSSLError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorSSLError: Cannot connect to host discordapp.com:443 ssl:None [[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)]
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x10dcb76d8>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x10e7067b8>
Task was destroyed but it is pending!
task: <Task pending coro=<game_and_avatar() running at appuselfbot.py:759> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x10f200cd8>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<Todo.todo_timer() running at /Users/CS/Downloads/DiscordSB/Discord-Selfbot-master/cogs/todo.py:223> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x10f200c48>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<Debugger.redirection_clock() running at /Users/CS/Downloads/DiscordSB/Discord-Selfbot-master/cogs/debugger.py:377> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x10f200c18>()]>>
It is not advised to run the bot with root privileges.
Continuing logging in...
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/connector.py", line 822, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 804, in create_connection
    sock, protocol_factory, ssl, server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 830, in _create_connection_transport
    yield from waiter
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/sslproto.py", line 505, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/sslproto.py", line 201, in feed_ssldata
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "appuselfbot.py", line 911, in <module>
    bot.run(token, bot=False)
  File "/Users/CS/Library/Python/3.6/lib/python/site-packages/discord/client.py", line 568, in run
    return task.result()
  File "/Users/CS/Library/Python/3.6/lib/python/site-packages/discord/client.py", line 475, in start
    await self.login(*args, bot=bot)
  File "/Users/CS/Library/Python/3.6/lib/python/site-packages/discord/client.py", line 346, in login
    await self.http.static_login(token, bot=bot)
  File "/Users/CS/Library/Python/3.6/lib/python/site-packages/discord/http.py", line 247, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "/Users/CS/Library/Python/3.6/lib/python/site-packages/discord/http.py", line 154, in request
    async with self._session.request(method, url, **kwargs) as r:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/client.py", line 843, in __aenter__
    self._resp = await self._coro
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/client.py", line 366, in _request
    timeout=timeout
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/connector.py", line 445, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/connector.py", line 757, in _create_connection
    req, traces, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/connector.py", line 879, in _create_direct_connection
    raise last_exc
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/connector.py", line 862, in _create_direct_connection
    req=req, client_error=client_error)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/connector.py", line 827, in _wrap_create_connection
    raise ClientConnectorSSLError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorSSLError: Cannot connect to host discordapp.com:443 ssl:None [[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)]
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x10dcb6748>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x10e705828>
Task was destroyed but it is pending!
task: <Task pending coro=<game_and_avatar() running at appuselfbot.py:759> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x10f200cd8>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<Todo.todo_timer() running at /Users/CS/Downloads/DiscordSB/Discord-Selfbot-master/cogs/todo.py:223> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x10f200c48>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<Debugger.redirection_clock() running at /Users/CS/Downloads/DiscordSB/Discord-Selfbot-master/cogs/debugger.py:377> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x10f200c18>()]>>
It is not advised to run the bot with root privileges.
Continuing logging in...
^CTraceback (most recent call last):
  File "loopself.py", line 18, in <module>
    subprocess.call(params)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 269, in call
    return p.wait(timeout=timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1457, in wait
    (pid, sts) = self._try_wait(0)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1404, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)

**Comment by LyricLy** [comment]
Navigate to your Applications/Python 3.6/ folder and double click `Install Certificates.command`.

**Comment by CS223** [comment]
Okay thanks but I get this error now 

Starting bot...
It is not advised to run the bot with root privileges.
Continuing logging in...
Task exception was never retrieved
future: <Task finished coro=<ConnectionState._delay_ready() done, defined at /var/root/Library/Python/3.6/lib/python/site-packages/discord/state.py:276> exception=TypeError('zip argument #1 must support iteration',)>
Traceback (most recent call last):
  File "/var/root/Library/Python/3.6/lib/python/site-packages/discord/state.py", line 288, in _delay_ready
    guilds = next(zip(*self._ready_state.guilds), [])
TypeError: zip argument #1 must support iteration

**Comment by appu1232** [comment]
Uh are you on the latest update? I pushed an update last night to fix the zip error.

**Comment by CS223** [comment]
Thanks for the help the bot works fine now all I needed to do was update it
