### ISSUE TITLE
cogs

### ISSUE THREAD

**Issue by emiruski** [appu1232/Discord-Selfbot#359]
nothing in the cog subcommands work.

`Traceback (most recent call last):
  File "C:\Users\NAS\AppData\Roaming\Python\Python36\site-packages\discord\ext\commands\bot.py", line 876, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\NAS\AppData\Roaming\Python\Python36\site-packages\discord\ext\commands\core.py", line 916, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "C:\Users\NAS\AppData\Roaming\Python\Python36\site-packages\discord\ext\commands\core.py", line 506, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\NAS\AppData\Roaming\Python\Python36\site-packages\discord\ext\commands\core.py", line 69, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

here's the error.

**Comment by LyricLy** [comment]
Duplicate of #337.
