### ISSUE TITLE
Error when accessing Cog list

### ISSUE THREAD

**Issue by HeyListenNavi** [appu1232/Discord-Selfbot#368]
```
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001985832CCF8>
Ignoring exception in command list
Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Python\Python35\site-packages\discord\ext\commands\core.py", line 60, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\Owner\Documents\Bots\Discord-Selfbot\cogs\cog_download.py", line 138, in list
    found_cog = response.json()
  File "C:\Users\Owner\AppData\Roaming\Python\Python35\site-packages\requests\models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python35\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python35\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python35\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Python\Python35\site-packages\discord\ext\commands\bot.py", line 876, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Owner\AppData\Roaming\Python\Python35\site-packages\discord\ext\commands\core.py", line 916, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "C:\Users\Owner\AppData\Roaming\Python\Python35\site-packages\discord\ext\commands\core.py", line 506, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\Owner\AppData\Roaming\Python\Python35\site-packages\discord\ext\commands\core.py", line 69, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by ProgramFreakHD** [comment]
Ihave the same problem.
