### ISSUE TITLE
Multiple commands not working (ud, poll, mal, etc.)

### ISSUE THREAD

**Issue by cr4nkapotomus** [appu1232/Discord-Selfbot#388]
>poll favorite color? = green | red | blue
:robot: An error occurred with the poll command. Check the console for details.

```
Ignoring exception in command poll
Traceback (most recent call last):
  File "C:\Users\cr4nk\AppData\Roaming\Python\Python36\site-packages\discord\ext\commands\core.py", line 60, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\cr4nk\Desktop\discordself\Discord-Selfbot-master\Discord-Selfbot-master\cogs\utility.py", line 309, in poll
    poll = await loop.run_in_executor(None, strawpy.create_poll, title.strip(), options)
  File "C:\Users\cr4nk\AppData\Local\Programs\Python\Python36\lib\concurrent\futures\thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\cr4nk\AppData\Roaming\Python\Python36\site-packages\strawpy\strawpy.py", line 46, in create_poll
    return StrawPoll(requests.post('http://strawpoll.me/api/v2/polls', data=json.dumps(query)))
  File "C:\Users\cr4nk\AppData\Roaming\Python\Python36\site-packages\strawpy\strawpy.py", line 117, in __init__
    self.response_json = strawpoll_response.json()
  File "C:\Users\cr4nk\AppData\Roaming\Python\Python36\site-packages\requests\models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\cr4nk\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\cr4nk\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\cr4nk\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 3 column 1 (char 2)

`The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\cr4nk\AppData\Roaming\Python\Python36\site-packages\discord\ext\commands\bot.py", line 876, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\cr4nk\AppData\Roaming\Python\Python36\site-packages\discord\ext\commands\core.py", line 506, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\cr4nk\AppData\Roaming\Python\Python36\site-packages\discord\ext\commands\core.py", line 69, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: JSONDecodeError: Expecting value: line 3 column 1 (char 2)
```

> :robot: An error occurred with the ud command. Check the console for details.

```
Ignoring exception in command ud
Traceback (most recent call last):
  File "C:\Users\cr4nk\AppData\Roaming\Python\Python36\site-packages\discord\ext\commands\core.py", line 60, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\cr4nk\Desktop\discordself\Discord-Selfbot-master\Discord-Selfbot-master\cogs\utility.py", line 467, in ud
    if result["tags"]:
KeyError: 'tags'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\cr4nk\AppData\Roaming\Python\Python36\site-packages\discord\ext\commands\bot.py", line 876, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\cr4nk\AppData\Roaming\Python\Python36\site-packages\discord\ext\commands\core.py", line 506, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\cr4nk\AppData\Roaming\Python\Python36\site-packages\discord\ext\commands\core.py", line 69, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: KeyError: 'tags'
```

>mal anime Ghost in the Shell
:robot: Searching...
:robot: An error occurred with the anime command. Check the console for details.
```

Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000025A624A0E48>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x0000025A62B565F8>, 442562.687)]']
connector: <aiohttp.connector.TCPConnector object at 0x0000025A62A95D68>
Ignoring exception in command anime
Traceback (most recent call last):
  File "C:\Users\cr4nk\AppData\Roaming\Python\Python36\site-packages\aiohttp\connector.py", line 822, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
  File "C:\Users\cr4nk\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 778, in create_connection
    raise exceptions[0]
  File "C:\Users\cr4nk\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 765, in create_connection
    yield from self.sock_connect(sock, address)
  File "C:\Users\cr4nk\AppData\Local\Programs\Python\Python36\lib\asyncio\selector_events.py", line 450, in sock_connect
    return (yield from fut)
  File "C:\Users\cr4nk\AppData\Local\Programs\Python\Python36\lib\asyncio\selector_events.py", line 480, in _sock_connect_cb
    raise OSError(err, 'Connect call failed %s' % (address,))
ConnectionRefusedError: [Errno 10061] Connect call failed ('67.227.226.240', 443)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\cr4nk\AppData\Roaming\Python\Python36\site-packages\discord\ext\commands\core.py", line 60, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\cr4nk\Desktop\discordself\Discord-Selfbot-master\Discord-Selfbot-master\cogs\mal.py", line 86, in anime
    results = await self.t_client.get_anime(int(anime_id[0]))
  File "C:\Users\cr4nk\AppData\Roaming\Python\Python36\site-packages\tokage\client.py", line 84, in get_anime
    response_json = await self.request(ANIME_URL + str(target_id))
  File "C:\Users\cr4nk\AppData\Roaming\Python\Python36\site-packages\tokage\client.py", line 76, in request
    async with self.session.get(url) as resp:
  File "C:\Users\cr4nk\AppData\Roaming\Python\Python36\site-packages\aiohttp\client.py", line 843, in __aenter__
    self._resp = await self._coro
  File "C:\Users\cr4nk\AppData\Roaming\Python\Python36\site-packages\aiohttp\client.py", line 366, in _request
    timeout=timeout
  File "C:\Users\cr4nk\AppData\Roaming\Python\Python36\site-packages\aiohttp\connector.py", line 445, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\cr4nk\AppData\Roaming\Python\Python36\site-packages\aiohttp\connector.py", line 757, in _create_connection
    req, traces, timeout)
  File "C:\Users\cr4nk\AppData\Roaming\Python\Python36\site-packages\aiohttp\connector.py", line 879, in _create_direct_connection
    raise last_exc
  File "C:\Users\cr4nk\AppData\Roaming\Python\Python36\site-packages\aiohttp\connector.py", line 862, in _create_direct_connection
    req=req, client_error=client_error)
  File "C:\Users\cr4nk\AppData\Roaming\Python\Python36\site-packages\aiohttp\connector.py", line 829, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.jikan.me:443 ssl:None [Connect call failed ('67.227.226.240', 443)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\cr4nk\AppData\Roaming\Python\Python36\site-packages\discord\ext\commands\bot.py", line 876, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\cr4nk\AppData\Roaming\Python\Python36\site-packages\discord\ext\commands\core.py", line 916, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "C:\Users\cr4nk\AppData\Roaming\Python\Python36\site-packages\discord\ext\commands\core.py", line 506, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\cr4nk\AppData\Roaming\Python\Python36\site-packages\discord\ext\commands\core.py", line 69, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ClientConnectorError: Cannot connect to host api.jikan.me:443 ssl:None [Connect call failed ('67.227.226.240', 443)]
```

Any ideas? Mostly everything else works. But I am sure there are other things that aren't working for me at the moment as well.
I am also having an issue when I add custom commands with images, they are not embed, but just posting the link of the images.

**Comment by appu1232** [comment]
MyAnimeList API has been down for a while, this likely won't be fixed any time soon. As for ud and poll, there seems to have been changes to the site which we haven't had a chance to update yet.

**Comment by cr4nkapotomus** [comment]
Ahh, roger. Thank you, will be looking forward to the update.

**Comment by LyricLy** [comment]
Update is here. `ud` is fixed, `poll` has been replaced with the old `rpoll`, and `mal` has been removed.
