### ISSUE TITLE
Am I the only one unable to use the cog list command?

### ISSUE THREAD

**Issue by xyn-n** [appu1232/Discord-Selfbot#398]
Whenever I type ">cog list" I get an error message. 

[https://i.imgur.com/yKQx3VX.png](url)

Am I the only one getting this?

**Comment by clragon** [comment]
Not at all. It doesnt work for me either.

**Comment by karb0n13** [comment]
getting errors for all of the 'cog' sub commands.
[error on Ubuntu 18.04](https://i.imgur.com/tGerHqJ.png)

**Comment by xyn-n** [comment]
> getting errors for all of the 'cog' sub commands.
> [error on Ubuntu 18.04](https://i.imgur.com/tGerHqJ.png)

I'm not sure why you're getting those errors. I only have it for >cog list as far as I know. I'll try it out next time I'm on Discord.

**Comment by clragon** [comment]
```Ignoring exception in command list                                                                               [2/639]Traceback (most recent call last):                                                                                        File "/home/clragon/.local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 60, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/clragon/selfbot/cogs/cog_download.py", line 138, in list
    found_cog = response.json()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/clragon/.local/lib/python3.5/site-packages/discord/ext/commands/bot.py", line 876, in invoke
    await ctx.command.invoke(ctx)
  File "/home/clragon/.local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 916, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "/home/clragon/.local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 506, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/clragon/.local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 69, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: JSONDecodeError: Expecting value: line 1 co
lumn 1 (char 0)```

errors on my end

**Comment by LyricLy** [comment]
I was under the impression that this was fixed. I'll check it out soon.

**Comment by LyricLy** [comment]
`view`, `install`, `uninstall` and `update` seem to be working fine, while I just fixed `list`.

**Comment by xyn-n** [comment]
> `view`, `install`, `uninstall` and `update` seem to be working fine, while I just fixed `list`.

It's a bit slow, but atleast it works. Thanks! <3
