### ISSUE TITLE
urban dictionary command broken

### ISSUE THREAD

**Issue by clragon** [appu1232/Discord-Selfbot#403]
```
Ignoring exception in command ud
Traceback (most recent call last):
  File "/home/clragon/.local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 60, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/clragon/selfbot/cogs/utility.py", line 467, in ud
    if result["tags"]:
KeyError: 'tags'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/clragon/.local/lib/python3.5/site-packages/discord/ext/commands/bot.py", line 876, in invoke
    await ctx.command.invoke(ctx)
  File "/home/clragon/.local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 506, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/clragon/.local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 69, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: KeyError: 'tags'
```

I get this error when running the `ud` command.

**Comment by LyricLy** [comment]
Are you on the latest version?

**Comment by clragon** [comment]
@LyricLy
yes

_Sent from my Galaxy S8+ using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by LyricLy** [comment]
Resolved.

**Comment by clragon** [comment]
It's still broken though? :thinking:

**Comment by LyricLy** [comment]
The line with this error no longer exists on the `master` branch, so that exact issue must no longer exist.
