### ISSUE TITLE
AttributeError in /cogs/track.py for messages in DM's

### ISSUE THREAD

**Issue by MyriaCore** [appu1232/Discord-Selfbot#408]
It'd be great if support for DMs was added.

Most of the problems with DMs seem to be associated with times the bot tries to get channel and guild info. I'll try my best to look into it myself and document here as needed, but as I said, I'm not super familiar with discord.py.

**Comment by MyriaCore** [comment]
OK so It took a few year because of my schedule, but I glanced at the code a bit and the presupposition that any message has to come with a channel or guild is all over the codebase. Maybe I'm not following something correctly, but it seems like it'd be a harder fix than I thought. If I have time, I might try to learn discord.py and refactor it myself. If I end up making something worth using, I'll add a pull request. People more experienced than me should also work on this though at some point.

**Comment by LyricLy** [comment]
Every message does come with a channel, but in a DM it will be a DMChannel instead of a Channel, which doesn't have every attribute Channel has.

**Comment by MyriaCore** [comment]
Right, I understand. IDK how I could help then, I clearly don't really know what I'm doing here 😅

**Comment by CamperGuy** [comment]
It used to work perfectly fine for me until I had some issues with an unclosed client connection.
I had changed my password to kick that session essentially but I still am not able to use the Bot in DMs whilst that used to work before and is still working for my friends.

**Comment by MyriaCore** [comment]
@CamperGuy I get unclosed client session issues too! I thought that was normal.

So it used to work in DMs at one point?

**Comment by MyriaCore** [comment]
**Hold on a sec.**

I just did some fiddling around, and the issue seems to be coming from the tracking functionality. 

When tracking is on, I get an unclosed connector (probably unrelated but worth mentioning), and an AtributeError with this traceback:
```
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\MyriaCore\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 220, in _run_event
      await coro(*args, **kwargs)
  File "appuselfbot.py", line 730, in on_message                                                                            
      await bot.process_commands(message)
  File "C:\Users\MyriaCore\AppData\Roaming\Python\Python36\site-packages\discord\ext\commands\bot.py", line 905, in process_commands
      await self.invoke(ctx)
  File "C:\Users\MyriaCore\AppData\Roaming\Python\Python36\site-packages\discord\ext\commands\bot.py", line 876, in invoke                                                                                                                          
      await ctx.command.invoke(ctx)
  File "C:\Users\MyriaCore\AppData\Roaming\Python\Python36\site-packages\discord\ext\commands\core.py", line 499, in invoke
      await self.prepare(ctx)                                                                                               
File "C:\Users\MyriaCore\AppData\Roaming\Python\Python36\site-packages\discord\ext\commands\core.py", line 465, in prepare                                                                                                                        
      await self.call_before_hooks(ctx)
  File "C:\Users\MyriaCore\AppData\Roaming\Python\Python36\site-packages\discord\ext\commands\core.py", line 433, in call_before_hooks
    await hook(ctx)                                                                                                       
File "D:\Libraries\Downloads\Discord-Selfbot-master\cogs\track.py", line 32, in register_command
    async with self.bot.session.post(self.url + "/command", data={"command_name": ctx.command.name, "guild_id": str(ctx.guild.id), "guild_name": ctx.guild.name}) as resp:
AttributeError: 'NoneType' object has no attribute 'id'
```
![image](https://user-images.githubusercontent.com/35076430/47269709-bb753500-d52f-11e8-86e9-fe0252c90a00.png)

When I have tracking off, all is well. No attribute error, the bot works as intended in DM's, and no unclosed connector (once again, this is probably unrelated, but I figured I'd mention it):
![image](https://user-images.githubusercontent.com/35076430/47269746-3cccc780-d530-11e8-9b74-d929498e04cf.png)

**Comment by MyriaCore** [comment]
I can spell I promise

**Comment by MyriaCore** [comment]
@LyricLy I haven't tested your fix yet, but if you have and think it's all good feel free to close this issue! Thanks so much for bearing with me!
