### ISSUE TITLE
Google search error

### ISSUE THREAD

**Issue by KuroSenseii** [appu1232/Discord-Selfbot#419]
When i type exemple *g what is google i have this error

`
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 876, in invoke
    await ctx.command.invoke(ctx)
  File "/root/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 506, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/root/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 69, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: KeyError: 'items'
`

**Comment by KuroSenseii** [comment]
2 month never anwser... nice
