### ISSUE TITLE
Error when using commands in pms

### ISSUE THREAD

**Issue by ghost** [appu1232/Discord-Selfbot#421]
```
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Administrator.MAK-MAIL\AppData\Roaming\Python\Python35\site-pac
kages\discord\client.py", line 220, in _run_event
    await coro(*args, **kwargs)
  File "appuselfbot.py", line 734, in on_message
    await bot.process_commands(message)
  File "C:\Users\Administrator.MAK-MAIL\AppData\Roaming\Python\Python35\site-pac
kages\discord\ext\commands\bot.py", line 905, in process_commands
    await self.invoke(ctx)
  File "C:\Users\Administrator.MAK-MAIL\AppData\Roaming\Python\Python35\site-pac
kages\discord\ext\commands\bot.py", line 876, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Administrator.MAK-MAIL\AppData\Roaming\Python\Python35\site-pac
kages\discord\ext\commands\core.py", line 899, in invoke
    await self.prepare(ctx)
  File "C:\Users\Administrator.MAK-MAIL\AppData\Roaming\Python\Python35\site-pac
kages\discord\ext\commands\core.py", line 465, in prepare
    await self.call_before_hooks(ctx)
  File "C:\Users\Administrator.MAK-MAIL\AppData\Roaming\Python\Python35\site-pac
kages\discord\ext\commands\core.py", line 433, in call_before_hooks
    await hook(ctx)
  File "C:\Users\Administrator.MAK-MAIL\Desktop\Selfbot\cogs\track.py", line 32,
 in register_command
    async with self.bot.session.post(self.url + "/command", data={"command_name"
: ctx.command.name, "guild_id": str(ctx.guild.id) if ctx.guild else str(ctx.chan
nel.recipient.id), "guild_name": ctx.guild.name}) as resp:
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by Rerd** [comment]
Was there an update I didn't get, or...
