### ISSUE TITLE
Erreur with cog list

### ISSUE THREAD

**Issue by KuroSenseii** [appu1232/Discord-Selfbot#436]
error with command Cog list

'unclosed client session' and 'unclosed connector' are not errors
--------------------------
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f2f2449f358>
Ignoring exception in command list
Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 60, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/bot/Discord-Selfbot/cogs/cog_download.py", line 138, in list
    found_cog = response.json()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 876, in invoke
    await ctx.command.invoke(ctx)
  File "/root/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 916, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "/root/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 506, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/root/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 69, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by nicefunfungal** [comment]
Excuse me but, did you ever figure out the solution to this?
