### ISSUE TITLE
Logging error

### ISSUE THREAD

**Issue by DexStarrUnderscore** [appu1232/Discord-Selfbot#437]
`--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Avery\AppData\Local\Programs\Python\Python35\lib\logging\handlers.py", line 71, in emit
    if self.shouldRollover(record):
  File "C:\Users\Avery\AppData\Local\Programs\Python\Python35\lib\logging\handlers.py", line 188, in shouldRollover
    self.stream.seek(0, 2)  #due to non-posix-compliant Windows feature
OSError: [Errno 22] Invalid argument
Call stack:
  File "appuselfbot.py", line 926, in <module>
    bot.run(token, bot=False)
  File "C:\Users\Avery\AppData\Roaming\Python\Python35\site-packages\discord\client.py", line 557, in run
    loop.run_forever()
  File "C:\Users\Avery\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 421, in run_forever
    self._run_once()
  File "C:\Users\Avery\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 1425, in _run_once
    handle._run()
  File "C:\Users\Avery\AppData\Local\Programs\Python\Python35\lib\asyncio\events.py", line 127, in _run
    self._callback(*self._args)
  File "C:\Users\Avery\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 321, in _wakeup
    self._step()
  File "C:\Users\Avery\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 240, in _step
    result = coro.send(None)
  File "C:\Users\Avery\AppData\Roaming\Python\Python35\site-packages\discord\client.py", line 476, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\Avery\AppData\Roaming\Python\Python35\site-packages\discord\client.py", line 398, in connect
    await self._connect()
  File "C:\Users\Avery\AppData\Roaming\Python\Python35\site-packages\discord\client.py", line 361, in _connect
    await self.ws.poll_event()
  File "C:\Users\Avery\AppData\Roaming\Python\Python35\site-packages\discord\gateway.py", line 444, in poll_event
    await self.received_message(msg)
  File "C:\Users\Avery\AppData\Roaming\Python\Python35\site-packages\discord\gateway.py", line 398, in received_message
    func(data)
  File "C:\Users\Avery\AppData\Roaming\Python\Python35\site-packages\discord\state.py", line 774, in parse_guild_members_chunk
    log.info('Processed a chunk for %s members in guild ID %s.', len(members), guild_id)
Message: 'Processed a chunk for %s members in guild ID %s.'
Arguments: (1000, 507553679046475784)
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Avery\AppData\Local\Programs\Python\Python35\lib\logging\handlers.py", line 71, in emit
    if self.shouldRollover(record):
  File "C:\Users\Avery\AppData\Local\Programs\Python\Python35\lib\logging\handlers.py", line 188, in shouldRollover
    self.stream.seek(0, 2)  #due to non-posix-compliant Windows feature
OSError: [Errno 22] Invalid argument
Call stack:
  File "appuselfbot.py", line 926, in <module>
    bot.run(token, bot=False)
  File "C:\Users\Avery\AppData\Roaming\Python\Python35\site-packages\discord\client.py", line 557, in run
    loop.run_forever()
  File "C:\Users\Avery\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 421, in run_forever
    self._run_once()
  File "C:\Users\Avery\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 1425, in _run_once
    handle._run()
  File "C:\Users\Avery\AppData\Local\Programs\Python\Python35\lib\asyncio\events.py", line 127, in _run
    self._callback(*self._args)
  File "C:\Users\Avery\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 321, in _wakeup
    self._step()
  File "C:\Users\Avery\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 240, in _step
    result = coro.send(None)
  File "C:\Users\Avery\AppData\Roaming\Python\Python35\site-packages\discord\client.py", line 476, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\Avery\AppData\Roaming\Python\Python35\site-packages\discord\client.py", line 398, in connect
    await self._connect()
  File "C:\Users\Avery\AppData\Roaming\Python\Python35\site-packages\discord\client.py", line 361, in _connect
    await self.ws.poll_event()
  File "C:\Users\Avery\AppData\Roaming\Python\Python35\site-packages\discord\gateway.py", line 444, in poll_event
    await self.received_message(msg)
  File "C:\Users\Avery\AppData\Roaming\Python\Python35\site-packages\discord\gateway.py", line 398, in received_message
    func(data)
  File "C:\Users\Avery\AppData\Roaming\Python\Python35\site-packages\discord\state.py", line 774, in parse_guild_members_chunk
    log.info('Processed a chunk for %s members in guild ID %s.', len(members), guild_id)
Message: 'Processed a chunk for %s members in guild ID %s.'
Arguments: (1000, 507553679046475784)
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Avery\AppData\Local\Programs\Python\Python35\lib\logging\handlers.py", line 71, in emit
    if self.shouldRollover(record):
  File "C:\Users\Avery\AppData\Local\Programs\Python\Python35\lib\logging\handlers.py", line 188, in shouldRollover
    self.stream.seek(0, 2)  #due to non-posix-compliant Windows feature
OSError: [Errno 22] Invalid argument
Call stack:
  File "appuselfbot.py", line 926, in <module>
    bot.run(token, bot=False)
  File "C:\Users\Avery\AppData\Roaming\Python\Python35\site-packages\discord\client.py", line 557, in run
    loop.run_forever()
  File "C:\Users\Avery\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 421, in run_forever
    self._run_once()
  File "C:\Users\Avery\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 1425, in _run_once
    handle._run()
  File "C:\Users\Avery\AppData\Local\Programs\Python\Python35\lib\asyncio\events.py", line 127, in _run
    self._callback(*self._args)
  File "C:\Users\Avery\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 321, in _wakeup
    self._step()
  File "C:\Users\Avery\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 240, in _step
    result = coro.send(None)
  File "C:\Users\Avery\AppData\Roaming\Python\Python35\site-packages\discord\client.py", line 476, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\Avery\AppData\Roaming\Python\Python35\site-packages\discord\client.py", line 398, in connect
    await self._connect()
  File "C:\Users\Avery\AppData\Roaming\Python\Python35\site-packages\discord\client.py", line 361, in _connect
    await self.ws.poll_event()
  File "C:\Users\Avery\AppData\Roaming\Python\Python35\site-packages\discord\gateway.py", line 444, in poll_event
    await self.received_message(msg)
  File "C:\Users\Avery\AppData\Roaming\Python\Python35\site-packages\discord\gateway.py", line 398, in received_message
    func(data)
  File "C:\Users\Avery\AppData\Roaming\Python\Python35\site-packages\discord\state.py", line 774, in parse_guild_members_chunk
    log.info('Processed a chunk for %s members in guild ID %s.', len(members), guild_id)
Message: 'Processed a chunk for %s members in guild ID %s.'
Arguments: (1000, 507553679046475784)
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Avery\AppData\Local\Programs\Python\Python35\lib\logging\handlers.py", line 71, in emit
    if self.shouldRollover(record):
  File "C:\Users\Avery\AppData\Local\Programs\Python\Python35\lib\logging\handlers.py", line 188, in shouldRollover
    self.stream.seek(0, 2)  #due to non-posix-compliant Windows feature
OSError: [Errno 22] Invalid argument
Call stack:
  File "appuselfbot.py", line 926, in <module>
    bot.run(token, bot=False)
  File "C:\Users\Avery\AppData\Roaming\Python\Python35\site-packages\discord\client.py", line 557, in run
    loop.run_forever()
  File "C:\Users\Avery\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 421, in run_forever
    self._run_once()
  File "C:\Users\Avery\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 1425, in _run_once
    handle._run()
  File "C:\Users\Avery\AppData\Local\Programs\Python\Python35\lib\asyncio\events.py", line 127, in _run
    self._callback(*self._args)
  File "C:\Users\Avery\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 321, in _wakeup
    self._step()
  File "C:\Users\Avery\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 240, in _step
    result = coro.send(None)
  File "C:\Users\Avery\AppData\Roaming\Python\Python35\site-packages\discord\client.py", line 476, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\Avery\AppData\Roaming\Python\Python35\site-packages\discord\client.py", line 398, in connect
    await self._connect()
  File "C:\Users\Avery\AppData\Roaming\Python\Python35\site-packages\discord\client.py", line 361, in _connect
    await self.ws.poll_event()
  File "C:\Users\Avery\AppData\Roaming\Python\Python35\site-packages\discord\gateway.py", line 444, in poll_event
    await self.received_message(msg)
  File "C:\Users\Avery\AppData\Roaming\Python\Python35\site-packages\discord\gateway.py", line 398, in received_message
    func(data)
  File "C:\Users\Avery\AppData\Roaming\Python\Python35\site-packages\discord\state.py", line 774, in parse_guild_members_chunk
    log.info('Processed a chunk for %s members in guild ID %s.', len(members), guild_id)
Message: 'Processed a chunk for %s members in guild ID %s.'
Arguments: (1000, 507553679046475784)`
It spams this stuff whenever I run the bot.
It puts my stream status back on but no commands work.

**Comment by gear4s** [comment]
this is a problem when rotating large log files and has been in python for years
