### ISSUE TITLE
lxml install problems

### ISSUE THREAD

**Issue by MrZeroLord** [appu1232/Discord-Selfbot#447]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MrZero\AppData\Roaming\Python\Python37\site-packages\pip\_internal\commands\install.py", line 503, in _warn_about_conflicts
    package_set, _dep_info = check_install_conflicts(to_install)
  File "C:\Users\MrZero\AppData\Roaming\Python\Python37\site-packages\pip\_internal\operations\check.py", line 108, in check_install_conflicts
    package_set, _ = create_package_set_from_installed()
  File "C:\Users\MrZero\AppData\Roaming\Python\Python37\site-packages\pip\_internal\operations\check.py", line 47, in create_package_set_from_installed
    package_set[name] = PackageDetails(dist.version, dist.requires())
  File "C:\Users\MrZero\AppData\Roaming\Python\Python37\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2635, in requires
    dm = self._dep_map
  File "C:\Users\MrZero\AppData\Roaming\Python\Python37\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2899, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "C:\Users\MrZero\AppData\Roaming\Python\Python37\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2908, in _compute_dependencies
    for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
  File "C:\Users\MrZero\AppData\Roaming\Python\Python37\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2890, in _parsed_pkg_info
    metadata = self.get_metadata(self.PKG_INFO)
  File "C:\Users\MrZero\AppData\Roaming\Python\Python37\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1410, in get_metadata
    value = self._get(self._fn(self.egg_info, name))
  File "C:\Users\MrZero\AppData\Roaming\Python\Python37\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1522, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\users\\mrzero\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\lxml-4.3.0.dist-info\\METADATA'
Installing collected packages: lxml, psutil, smmap2, gitdb2, GitPython, olefile, Pillow, pyfiglet, chardet, async-timeout, attrs, multidict, idna, yarl, aiohttp, tokage, pytz, pyjwt, PyGithub, websockets, discord.py
  Running setup.py install for lxml ... error
    Complete output from command C:\Users\MrZero\AppData\Local\Programs\Python\Python37\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\MrZero\\AppData\\Local\\Temp\\pip-install-xnt_tx1h\\lxml\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\MrZero\AppData\Local\Temp\pip-record-_pcawyts\install-record.txt --single-version-externally-managed --compile --user --prefix=:
    Building lxml version 3.8.0.
    Building without Cython.
    ERROR: b'Der Befehl "xslt-config" ist entweder falsch geschrieben oder\r\nkonnte nicht gefunden werden.\r\n'
    ** make sure the development packages of libxml2 and libxslt are installed **

    Using build configuration of libxslt
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\lxml
    copying src\lxml\builder.py -> build\lib.win-amd64-3.7\lxml
    copying src\lxml\cssselect.py -> build\lib.win-amd64-3.7\lxml
    copying src\lxml\doctestcompare.py -> build\lib.win-amd64-3.7\lxml
    copying src\lxml\ElementInclude.py -> build\lib.win-amd64-3.7\lxml
    copying src\lxml\pyclasslookup.py -> build\lib.win-amd64-3.7\lxml
    copying src\lxml\sax.py -> build\lib.win-amd64-3.7\lxml
    copying src\lxml\usedoctest.py -> build\lib.win-amd64-3.7\lxml
    copying src\lxml\_elementpath.py -> build\lib.win-amd64-3.7\lxml
    copying src\lxml\__init__.py -> build\lib.win-amd64-3.7\lxml
    creating build\lib.win-amd64-3.7\lxml\includes
    copying src\lxml\includes\__init__.py -> build\lib.win-amd64-3.7\lxml\includes
    creating build\lib.win-amd64-3.7\lxml\html
    copying src\lxml\html\builder.py -> build\lib.win-amd64-3.7\lxml\html
    copying src\lxml\html\clean.py -> build\lib.win-amd64-3.7\lxml\html
    copying src\lxml\html\defs.py -> build\lib.win-amd64-3.7\lxml\html
    copying src\lxml\html\diff.py -> build\lib.win-amd64-3.7\lxml\html
    copying src\lxml\html\ElementSoup.py -> build\lib.win-amd64-3.7\lxml\html
    copying src\lxml\html\formfill.py -> build\lib.win-amd64-3.7\lxml\html
    copying src\lxml\html\html5parser.py -> build\lib.win-amd64-3.7\lxml\html
    copying src\lxml\html\soupparser.py -> build\lib.win-amd64-3.7\lxml\html
    copying src\lxml\html\usedoctest.py -> build\lib.win-amd64-3.7\lxml\html
    copying src\lxml\html\_diffcommand.py -> build\lib.win-amd64-3.7\lxml\html
    copying src\lxml\html\_html5builder.py -> build\lib.win-amd64-3.7\lxml\html
    copying src\lxml\html\_setmixin.py -> build\lib.win-amd64-3.7\lxml\html
    copying src\lxml\html\__init__.py -> build\lib.win-amd64-3.7\lxml\html
    creating build\lib.win-amd64-3.7\lxml\isoschematron
    copying src\lxml\isoschematron\__init__.py -> build\lib.win-amd64-3.7\lxml\isoschematron
    copying src\lxml\lxml.etree.h -> build\lib.win-amd64-3.7\lxml
    copying src\lxml\lxml.etree_api.h -> build\lib.win-amd64-3.7\lxml
    copying src\lxml\includes\c14n.pxd -> build\lib.win-amd64-3.7\lxml\includes
    copying src\lxml\includes\config.pxd -> build\lib.win-amd64-3.7\lxml\includes
    copying src\lxml\includes\dtdvalid.pxd -> build\lib.win-amd64-3.7\lxml\includes
    copying src\lxml\includes\etreepublic.pxd -> build\lib.win-amd64-3.7\lxml\includes
    copying src\lxml\includes\htmlparser.pxd -> build\lib.win-amd64-3.7\lxml\includes
    copying src\lxml\includes\relaxng.pxd -> build\lib.win-amd64-3.7\lxml\includes
    copying src\lxml\includes\schematron.pxd -> build\lib.win-amd64-3.7\lxml\includes
    copying src\lxml\includes\tree.pxd -> build\lib.win-amd64-3.7\lxml\includes
    copying src\lxml\includes\uri.pxd -> build\lib.win-amd64-3.7\lxml\includes
    copying src\lxml\includes\xinclude.pxd -> build\lib.win-amd64-3.7\lxml\includes
    copying src\lxml\includes\xmlerror.pxd -> build\lib.win-amd64-3.7\lxml\includes
    copying src\lxml\includes\xmlparser.pxd -> build\lib.win-amd64-3.7\lxml\includes
    copying src\lxml\includes\xmlschema.pxd -> build\lib.win-amd64-3.7\lxml\includes
    copying src\lxml\includes\xpath.pxd -> build\lib.win-amd64-3.7\lxml\includes
    copying src\lxml\includes\xslt.pxd -> build\lib.win-amd64-3.7\lxml\includes
    copying src\lxml\includes\etree_defs.h -> build\lib.win-amd64-3.7\lxml\includes
    copying src\lxml\includes\lxml-version.h -> build\lib.win-amd64-3.7\lxml\includes
    creating build\lib.win-amd64-3.7\lxml\isoschematron\resources
    creating build\lib.win-amd64-3.7\lxml\isoschematron\resources\rng
    copying src\lxml\isoschematron\resources\rng\iso-schematron.rng -> build\lib.win-amd64-3.7\lxml\isoschematron\resources\rng
    creating build\lib.win-amd64-3.7\lxml\isoschematron\resources\xsl
    copying src\lxml\isoschematron\resources\xsl\RNG2Schtrn.xsl -> build\lib.win-amd64-3.7\lxml\isoschematron\resources\xsl
    copying src\lxml\isoschematron\resources\xsl\XSD2Schtrn.xsl -> build\lib.win-amd64-3.7\lxml\isoschematron\resources\xsl
    creating build\lib.win-amd64-3.7\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_abstract_expand.xsl -> build\lib.win-amd64-3.7\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_dsdl_include.xsl -> build\lib.win-amd64-3.7\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_schematron_message.xsl -> build\lib.win-amd64-3.7\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_schematron_skeleton_for_xslt1.xsl -> build\lib.win-amd64-3.7\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_svrl_for_xslt1.xsl -> build\lib.win-amd64-3.7\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\readme.txt -> build\lib.win-amd64-3.7\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    running build_ext
    building 'lxml.etree' extension
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    creating build\temp.win-amd64-3.7\Release\src
    creating build\temp.win-amd64-3.7\Release\src\lxml
    E:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Isrc\lxml\includes -IC:\Users\MrZero\AppData\Local\Programs\Python\Python37\include -IC:\Users\MrZero\AppData\Local\Programs\Python\Python37\include "-IE:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IE:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IE:\Windows Kits\10\include\10.0.17763.0\ucrt" "-IE:\Windows Kits\10\include\10.0.17763.0\shared" "-IE:\Windows Kits\10\include\10.0.17763.0\um" "-IE:\Windows Kits\10\include\10.0.17763.0\winrt" "-IE:\Windows Kits\10\include\10.0.17763.0\cppwinrt" /Tcsrc\lxml\lxml.etree.c /Fobuild\temp.win-amd64-3.7\Release\src\lxml\lxml.etree.obj -w
    cl : Befehlszeile warning D9025 : "/W3" wird durch "/w" Ã¼berschrieben
    lxml.etree.c
    src\lxml\includes\etree_defs.h(14): fatal error C1083: Datei (Include) kann nicht geÃ¶ffnet werden: "libxml/xmlversion.h": No such file or directory
    Compile failed: command 'E:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    creating Users
    creating Users\MrZero
    creating Users\MrZero\AppData
    creating Users\MrZero\AppData\Local
    creating Users\MrZero\AppData\Local\Temp
    E:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I/usr/include/libxml2 "-IE:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IE:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IE:\Windows Kits\10\include\10.0.17763.0\ucrt" "-IE:\Windows Kits\10\include\10.0.17763.0\shared" "-IE:\Windows Kits\10\include\10.0.17763.0\um" "-IE:\Windows Kits\10\include\10.0.17763.0\winrt" "-IE:\Windows Kits\10\include\10.0.17763.0\cppwinrt" /TcC:\Users\MrZero\AppData\Local\Temp\xmlXPathInitfmp8w7pz.c /FoUsers\MrZero\AppData\Local\Temp\xmlXPathInitfmp8w7pz.obj
    xmlXPathInitfmp8w7pz.c
    C:\Users\MrZero\AppData\Local\Temp\xmlXPathInitfmp8w7pz.c(1): fatal error C1083: Datei (Include) kann nicht geÃ¶ffnet werden: "libxml/xpath.h": No such file or directory
    *********************************************************************************
    Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
    *********************************************************************************
    error: command 'E:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "C:\Users\MrZero\AppData\Local\Programs\Python\Python37\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\MrZero\\AppData\\Local\\Temp\\pip-install-xnt_tx1h\\lxml\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\MrZero\AppData\Local\Temp\pip-record-_pcawyts\install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in C:\Users\MrZero\AppData\Local\Temp\pip-install-xnt_tx1h\lxml\
Requirements installation failed. Perhaps some dependency is missing or access was denied? Possible solutions:
- Run as administrator
- Google the error
- Visit the Discord server for help
Press any key to exit.

**Comment by MrZeroLord** [comment]
Found Solution:

Version Python 3.6.5 is supported

**Comment by Anonwars** [comment]
I'm having a problem where it says cannot connect to this certain host.

**Comment by rmccrystal** [comment]
This problem also exists in the Dockerfile
