### ISSUE TITLE
Can't install requirements

### ISSUE THREAD

**Issue by Hate9** [appu1232/Discord-Selfbot#449]
>fatal: not a git repository (or any of the parent directories): .git
>This seems to be your first run. The setup will now proceed to download all required files. They will be downloaded to the same location as where this run.bat file is.
>Press any key to continue . . .
>Fetching origin
>remote: Enumerating objects: 5360, done.
>remote: Total 5360 (delta 0), reused 0 (delta 0), pack-reused 5360
>Receiving objects: 100% (5360/5360), 8.51 MiB | 5.17 MiB/s, done.
>Resolving deltas: 100% (3739/3739), done.
>From https://github.com/appu1232/Discord-Selfbot
> * [new branch]      dev             -> origin/dev
> * [new branch]      log-context-fix -> origin/log-context-fix
> * [new branch]      master          -> origin/master
> * [new tag]         v1.4.0          -> v1.4.0
> * [new tag]         v1.6.2          -> v1.6.2
> * [new tag]         v1.6.3          -> v1.6.3
> * [new tag]         v1.6.4          -> v1.6.4
> * [new tag]         v1.6.5          -> v1.6.5
> * [new tag]         v1.6.6          -> v1.6.6
> * [new tag]         v2.0.0          -> v2.0.0
> * [new tag]         v2.1.0          -> v2.1.0
>HEAD is now at 766b1e6 Merge branch 'master' of https://github.com/appu1232/Discord-Selfbot
>Checking/Installing requirements (takes some time on first install)...
>DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
>DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
>Collecting git+https://github.com/Rapptz/discord.py@184c4302c7fe17a31893f0accf197c975200d233 (from -r requirements.txt (line 1))
>  Cloning https://github.com/Rapptz/discord.py (to revision 184c4302c7fe17a31893f0accf197c975200d233) to c:\users\aidan\appdata\local\temp\pip-req-build-nppeomqw
>Collecting requests==2.12.4 (from -r requirements.txt (line 2))
>  Using cached https://files.pythonhosted.org/packages/ed/9e/60cc074968c095f728f0d8d28370e8d396fa60afb7582735563cccf223dd/requests-2.12.4-py2.py3-none-any.whl
>Exception:
>Traceback (most recent call last):
>  File "C:\Users\Aidan\AppData\Roaming\Python\Python34\site-packages\pip\_internal\cli\base_command.py", line 179, in main
>    status = self.run(options, args)
>  File "C:\Users\Aidan\AppData\Roaming\Python\Python34\site-packages\pip\_internal\commands\install.py", line 315, in run
>    resolver.resolve(requirement_set)
>  File "C:\Users\Aidan\AppData\Roaming\Python\Python34\site-packages\pip\_internal\resolve.py", line 131, in resolve
>    self._resolve_one(requirement_set, req)
>  File "C:\Users\Aidan\AppData\Roaming\Python\Python34\site-packages\pip\_internal\resolve.py", line 299, in _resolve_one
>    check_dist_requires_python(dist)
>  File "C:\Users\Aidan\AppData\Roaming\Python\Python34\site-packages\pip\_internal\utils\packaging.py", line 61, in check_dist_requires_python
>    pkg_info_dict = get_metadata(dist)
>  File "C:\Users\Aidan\AppData\Roaming\Python\Python34\site-packages\pip\_internal\utils\packaging.py", line 57, in get_metadata
>    return feed_parser.close()
>  File "C:\Python34\lib\email\feedparser.py", line 170, in close
>    self._call_parse()
>  File "C:\Python34\lib\email\feedparser.py", line 163, in _call_parse
>    self._parse()
>  File "C:\Python34\lib\email\feedparser.py", line 449, in _parsegen
>    self._cur.set_payload(EMPTYSTRING.join(lines))
>  File "C:\Python34\lib\email\message.py", line 311, in set_payload
>    " payload") from None
>TypeError: charset argument must be specified when non-ASCII characters are used in the payload
>Requirements installation failed. Perhaps some dependency is missing or access was denied? Possible solutions:
>- Run as administrator
>- Google the error
>- Visit the Discord server for help
>Press any key to exit.

**Comment by Hate9** [comment]
Apparently, I had an old version of Python installed, and it was trying to use that.
