### ISSUE TITLE
Not working on Raspberry Pi 3 - Raspbian PIXEL

### ISSUE THREAD

**Issue by Johnystar** [appu1232/Discord-Selfbot#90]
When trying to install the requirements, I get this:
```
 In file included from src/lxml/lxml.etree.c:515:0:
    src/lxml/includes/etree_defs.h:14:31: fatal error: libxml/xmlversion.h: No such file or directory
     #include "libxml/xmlversion.h"
                                   ^
    compilation terminated.
    Compile failed: command 'gcc' failed with exit status 1
    creating tmp
    cc -I/usr/include/libxml2 -c /tmp/xmlXPathInit1be45_qt.c -o tmp/xmlXPathInit1be45_qt.o
    /tmp/xmlXPathInit1be45_qt.c:1:26: fatal error: libxml/xpath.h: No such file or directory
     #include "libxml/xpath.h"
                              ^
    compilation terminated.
    *********************************************************************************
    Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
    *********************************************************************************
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/local/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-1tsdvukb/lxml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-n24km37v-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-1tsdvukb/lxml/
```

I used the command pip3 `install --user -r requirements.txt` both with sudo and without sudo, because  the run_linuxmac.sh file didn't work either:
WITHOUT SUDO:
```
pi@rpi3:~/DISCORD_SELF_BOT $ ./run_linuxmac.sh
./run_linuxmac.sh: line 1: $'\r': command not found
./run_linuxmac.sh: line 2: $'\r': command not found
Warning: this script is still an alpha, expect bugs
./run_linuxmac.sh: line 4: $'\r': command not found
./run_linuxmac.sh: line 5: syntax error near unexpected token `$'{\r''
'/run_linuxmac.sh: line 5: `updater () {

```
WITH SUDO:
```
pi@rpi3:~/DISCORD_SELF_BOT $ sudo ./run_linuxmac.sh
: not foundmac.sh: 1: ./run_linuxmac.sh:
: not foundmac.sh: 2: ./run_linuxmac.sh:
Warning: this script is still an alpha, expect bugs
: not foundmac.sh: 4: ./run_linuxmac.sh:
Starting auto-update
./run_linuxmac.sh: 131: ./run_linuxmac.sh: Syntax error: "elif" unexpected (expecting "then")
```
I only got this far when I deleted the `#!/bin/bash` line.
With `#!/bin/bash`:
```
pi@rpi3:~/DISCORD_SELF_BOT $ ./run_linuxmac.sh
-bash: ./run_linuxmac.sh: /bin/bash^M: bad interpreter: No such file or directory
```
- I know that it is still in Alpha, but I thought that I'd report this issue anyway.
- I think that the APIs maybe not compatible with Raspberry Pi

It would be really cool if it would be possible to run the selfbot script on Raspberry Pi too, because then I would be able to keep it running 24/7 and wouldn't have to start it manually every time I want to use it (or add it to the Windows startup folder (I'm a Windows user)). Also then I would be able to use it without having to keep my pc running.

Thank you for your response, I hope I included everything and sorry for my bad English.

**Comment by appu1232** [comment]
The compile errors at the top are because of some missing dependencies. Run `sudo apt-get install libxml2 python3-dev gcc` then it should be fixed.

As for the run_linuxmac, you need to run it as `bash run_linuxmac.sh` not ./. If that still doesn't work then try redownloading the run_linuxmac.sh again.

**Comment by Johnystar** [comment]
Still not working. I redownloaded the whole bot again from GitHub and still nothing, still the same error. I found out that I already had libxml2, python3-dev and gcc installed, so I just made sure that everything is updated.
This is what I got:
```
Warning: this script is still an alpha, expect bugs
Starting auto-update
Fetching origin
From https://github.com/appu1232/Discord-Selfbot
 * branch            master     -> FETCH_HEAD
The bot is up to date.
Checking requirements...
Using global pip3 executable
Command "/usr/local/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-qumc909y/lxml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-zokr5f2o-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-qumc909y/lxml/
Requirements installation failed
```

**Comment by chenzw95** [comment]
Please ensure that you have `libxml2-dev` (or however the distro names the development package) installed. The library headers are required for the compilation to succeed.

**Comment by Johnystar** [comment]
So, I made sure that `libxml2-dev` is installed (I have Raspbian PIXEL, base on Debian) and this is what I got:
```
pi@rpi3:~/DISCORD_SELF_BOT $ bash run_linuxmac.sh
Warning: this script is still an alpha, expect bugs
Starting auto-update
Fetching origin
From https://github.com/appu1232/Discord-Selfbot
 * branch            master     -> FETCH_HEAD
The bot is up to date.
Checking requirements...
Using global pip3 executable
Command "/usr/local/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-dut3c3pt/lxml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-2jo9k9c_-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-dut3c3pt/lxml/
Requirements installation failed
```
(Tried bot with sudo and without sudo)

**Comment by chenzw95** [comment]
Run the pip3 command that you ran directly earlier on, and paste the command output again.

**Comment by Johnystar** [comment]
```
gcc -pthread -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Isrc/lxml/includes -I/usr/local/include/python3.5m -c src/lxml/lxml.etree.c -o build/temp.linux-armv7l-3.5/src/lxml/lxml.etree.o -w
    In file included from src/lxml/lxml.etree.c:515:0:
    src/lxml/includes/etree_defs.h:14:31: fatal error: libxml/xmlversion.h: No such file or directory
     #include "libxml/xmlversion.h"
                                   ^
    compilation terminated.
    Compile failed: command 'gcc' failed with exit status 1
    creating tmp
    cc -I/usr/include/libxml2 -c /tmp/xmlXPathInit568k8pd4.c -o tmp/xmlXPathInit568k8pd4.o
    cc tmp/xmlXPathInit568k8pd4.o -lxml2 -o a.out
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/local/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-g1xixm8p/lxml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-_vontju_-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-g1xixm8p/lxml/
```

**Comment by chenzw95** [comment]
Also check that you have `libxslt-dev` (or however your distro names the package) installed. This is an issue with your Linux environment.

**Comment by Johnystar** [comment]
```
pi@rpi3:~/DISCORD_SELF_BOT $ sudo apt-get install libxslt-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'libxslt1-dev' instead of 'libxslt-dev'
The following NEW packages will be installed:
  libxslt1-dev
0 upgraded, 1 newly installed, 0 to remove and 4 not upgraded.
Need to get 498 kB of archives.
After this operation, 2,193 kB of additional disk space will be used.
Get:1 http://mirrordirector.raspbian.org/raspbian/ jessie/main libxslt1-dev armhf 1.1.28-2+deb8u3 [498 kB]
Fetched 498 kB in 0s (580 kB/s)
Selecting previously unselected package libxslt1-dev:armhf.
(Reading database ... 116575 files and directories currently installed.)
Preparing to unpack .../libxslt1-dev_1.1.28-2+deb8u3_armhf.deb ...
Unpacking libxslt1-dev:armhf (1.1.28-2+deb8u3) ...
Processing triggers for man-db (2.7.5-1~bpo8+1) ...
Setting up libxslt1-dev:armhf (1.1.28-2+deb8u3) ...
pi@rpi3:~/DISCORD_SELF_BOT $ bash run_linuxmac.sh
Warning: this script is still an alpha, expect bugs
Starting auto-update
Fetching origin
remote: Counting objects: 37, done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 37 (delta 22), reused 30 (delta 15), pack-reused 0
Unpacking objects: 100% (37/37), done.
From https://github.com/appu1232/Discord-Selfbot
 * branch            master     -> FETCH_HEAD
   7d60d70..50bf2b0  master     -> origin/master
There is an update available. Download now? (y/n):y
Installing update
Updating to latest stable build.
From https://github.com/appu1232/Discord-Selfbot
 * branch            master     -> FETCH_HEAD
Updating 7d60d70..50bf2b0
Fast-forward
 appuselfbot.py    |  4 ++--
 cogs/fun.py       |  2 +-
 cogs/imagedump.py | 61 +++++++++++++++++++++++++++++--------------------------------
 requirements.txt  |  2 +-
 run.bat           |  2 +-
 5 files changed, 34 insertions(+), 37 deletions(-)
Update succeeded
Checking requirements...
Using global pip3 executable
Command "/usr/local/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-1gzd7jwn/Pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-anrr7r8k-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-1gzd7jwn/Pillow/
Requirements installation failed
```
Still not working... I hope that `libxslt-dev` and `libxslt1-dev` is the same thing. It should be..

**Comment by chenzw95** [comment]
Please stop running the bash script while troubleshooting this issue. We won't have the pip3 command output if you run the script. Run the pip3 command that you ran directly earlier on, and paste the command output again.

**Comment by Johnystar** [comment]
Okay, sorry. Give me a second.

**Comment by Johnystar** [comment]
```
The headers or library files could not be found for jpeg,
    a required dependency when compiling Pillow from source.

    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html

    Traceback (most recent call last):
      File "/tmp/pip-build-ftbsz8ec/Pillow/setup.py", line 776, in <module>
        zip_safe=not debug_build(), )
      File "/usr/local/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.5/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/lib/python3.5/distutils/command/install.py", line 539, in run
        self.run_command('build')
      File "/usr/local/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.5/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/local/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.5/distutils/command/build_ext.py", line 338, in run
        self.build_extensions()
      File "/tmp/pip-build-ftbsz8ec/Pillow/setup.py", line 566, in build_extensions
        raise RequiredDependencyException(f)
    __main__.RequiredDependencyException: jpeg

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ftbsz8ec/Pillow/setup.py", line 788, in <module>
        raise RequiredDependencyException(msg)
    __main__.RequiredDependencyException:

    The headers or library files could not be found for jpeg,
    a required dependency when compiling Pillow from source.

    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html



    ----------------------------------------
Command "/usr/local/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ftbsz8ec/Pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-arxmtlrz-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-ftbsz8ec/Pillow/
```
I'm guessing that I need to install something called `jpeg`. Didn't find anything like that though...

**Comment by Jan200101** [comment]
You are missing the requirements needed for Pillow.
Check [the Pillow Docs](https://pillow.readthedocs.io/en/latest/installation.html#external-libraries) to see what you need to install

**Comment by chenzw95** [comment]
No new updates after 2 weeks, please visit our Discord server if you still run into issues.
